// Generated by scripts/extract-recipe-data.mjs — DO NOT hand-edit.
// Curated library snapshots (Spoonacular Recipe JSON-LD parsed from a static build).
// Extend/refresh with scripts/snapshot-recipes.mjs when API quota is available.

import type { CuratedRecipeData } from './types'

export const recipeData: CuratedRecipeData[] = [
  {
    "id": 1063113,
    "title": "Scrambled tofu aka vegan scrambled eggs",
    "image": "https://img.spoonacular.com/recipes/1063113-556x370.jpg",
    "readyInMinutes": 45,
    "servings": 1,
    "extendedIngredients": [
      {
        "original": "1 tsp of cumin",
        "amount": 1,
        "unit": "tsp",
        "name": "of cumin"
      },
      {
        "original": "2 cloves of garlic",
        "amount": 2,
        "unit": "cloves",
        "name": "of garlic"
      },
      {
        "original": "olive oil"
      },
      {
        "original": "half an onion"
      },
      {
        "original": "pepper"
      },
      {
        "original": "salt"
      },
      {
        "original": "1 tsp of smoked paprika",
        "amount": 1,
        "unit": "tsp",
        "name": "of smoked paprika"
      },
      {
        "original": "handful of spinach"
      },
      {
        "original": "1 pack of tofu (I used Yutaka)",
        "amount": 1
      }
    ],
    "analyzedInstructions": [],
    "macros": {
      "calories": 527,
      "protein": 38,
      "carbs": 24,
      "fat": 33
    }
  },
  {
    "id": 1164981,
    "title": "Instant Pot Stuffed Spaghetti Squash",
    "image": "https://img.spoonacular.com/recipes/1164981-556x370.jpg",
    "readyInMinutes": 55,
    "servings": 2,
    "extendedIngredients": [
      {
        "original": "1 2-lb. spaghetti squash"
      },
      {
        "original": "1 tablespoon olive oil",
        "amount": 1,
        "unit": "tablespoon",
        "name": "olive oil"
      },
      {
        "original": "1/2 medium white onion, minced",
        "amount": 0.5
      },
      {
        "original": "3 cloves garlic, peeled and minced",
        "amount": 3,
        "unit": "cloves",
        "name": "garlic, peeled and minced"
      },
      {
        "original": "8 oz. crimini mushrooms, chopped",
        "amount": 8,
        "unit": "oz",
        "name": "crimini mushrooms, chopped"
      },
      {
        "original": "1/4 teaspoon salt",
        "amount": 0.25,
        "unit": "teaspoon",
        "name": "salt"
      },
      {
        "original": "1/4 teaspoon ground pepper",
        "amount": 0.25,
        "unit": "teaspoon",
        "name": "ground pepper"
      },
      {
        "original": "1/2 cup vegetable broth (but any kind works!)",
        "amount": 0.5,
        "unit": "cup",
        "name": "vegetable broth (but any kind works!)"
      },
      {
        "original": "4 cups chopped kale, deboned",
        "amount": 4,
        "unit": "cups",
        "name": "chopped kale, deboned"
      },
      {
        "original": "1/2 cup julienned sun-dried tomatoes (in oil)",
        "amount": 0.5,
        "unit": "cup",
        "name": "julienned sun-dried tomatoes (in oil)"
      },
      {
        "original": "1 tablespoon tomato paste",
        "amount": 1,
        "unit": "tablespoon",
        "name": "tomato paste"
      },
      {
        "original": "1/4 cup shaved parmesan",
        "amount": 0.25,
        "unit": "cup",
        "name": "shaved parmesan"
      },
      {
        "original": "Optional: 1/4 cup toasted pine nuts"
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "First, prepare the spaghetti squash by cutting off the stem end of the squash with a sharp knife. Set the spaghetti squash flat on a cutting board and carefully cut the squash in half (hot dog style)."
          },
          {
            "number": 2,
            "step": "Use a spoon to scoop out the seeds and then discard the seeds. Lightly season squash halves with salt and pepper. Set aside."
          },
          {
            "number": 3,
            "step": "Next, turn the on Instant Pot’s saute feature and add 1 tablespoon olive oil to the bottom of the pot."
          },
          {
            "number": 4,
            "step": "When the olive oil is fragrant, add onion to the pot and saute for 1 minute. Then, add garlic, chopped mushrooms, 1/4 teaspoon salt, and 1/4 teaspoon pepper and cook for an additional 2 minutes."
          },
          {
            "number": 5,
            "step": "Next, pour broth into the bottom of the pot and set the trivet on top of all of the vegetables."
          },
          {
            "number": 6,
            "step": "Place spaghetti squash halves on top of the trivet and cover the Instant Pot."
          },
          {
            "number": 7,
            "step": "Turn the pressure valve to seal and set the Instant Pot to manual >> high pressure for 6 minutes."
          },
          {
            "number": 8,
            "step": "It will take a few minutes for the Instant Pot to build pressure, but eventually it will count down from 6 minutes. When the timer goes off, quick release the Instant Pot."
          },
          {
            "number": 9,
            "step": "Then, carefully remove the squash and trivet from the Instant Pot and set aside."
          },
          {
            "number": 10,
            "step": "Turn the saute feature back on and add chopped kale, sun-dried tomatoes, and tomato paste to the pot."
          },
          {
            "number": 11,
            "step": "Saute everything together for 2-3 minutes or until the kale becomes softer and bright green."
          },
          {
            "number": 12,
            "step": "While the veggies are sauteeing, carefully scoop out the innards of the spaghetti squash. We like to use a fork to fluff the “squash noodles” and then scoop everything out. If you are serving this dish immediately, make sure to keep the squash skin intact so that you can serve it inside the squash half."
          },
          {
            "number": 13,
            "step": "Spoon the squash innards into the Instant Pot and saute everything together."
          },
          {
            "number": 14,
            "step": "Last, add parmesan cheese and mix again."
          },
          {
            "number": 15,
            "step": "Serve with toasted pine nuts and enjoy!"
          }
        ]
      }
    ],
    "macros": {
      "calories": 463,
      "protein": 18,
      "carbs": 53,
      "fat": 25
    }
  },
  {
    "id": 201159,
    "title": "Zesty Slow-Cooker Italian Pot Roast",
    "image": "https://img.spoonacular.com/recipes/201159-556x370.jpg",
    "readyInMinutes": 45,
    "servings": 6,
    "extendedIngredients": [
      {
        "original": "2 cups fresh OR frozen whole baby carrots",
        "amount": 2,
        "unit": "cups",
        "name": "fresh OR frozen whole baby carrots"
      },
      {
        "original": "2 1/2 pounds beef bottom round roast or 0 lb. beef chuck pot roast",
        "amount": 2.5,
        "unit": "pounds",
        "name": "beef bottom round roast or 0 lb. beef chuck pot roast"
      },
      {
        "original": "1 stalk celery, cut into 1",
        "amount": 1,
        "unit": "stalk",
        "name": "celery, cut into 1"
      },
      {
        "original": "1 can (10 3/4 oz.) Campbell's® Condensed Tomato Soup",
        "amount": 1,
        "unit": "can",
        "name": "(10 3/4 oz.) Campbell's® Condensed Tomato Soup"
      },
      {
        "original": "1 teaspoon each dried basil leaves, dried oregano leaves and dried parsley flakes, crushed",
        "amount": 1,
        "unit": "teaspoon",
        "name": "each dried basil leaves, dried oregano leaves and dried parsley flakes, crushed"
      },
      {
        "original": "1/2 teaspoon ground black pepper",
        "amount": 0.5,
        "unit": "teaspoon",
        "name": "ground black pepper"
      },
      {
        "original": "1 medium Italian plum tomato, diced",
        "amount": 1
      },
      {
        "original": "4 medium potatoes, cut into quarters (4 cups)",
        "amount": 4
      },
      {
        "original": "1 tablespoon chopped roasted garlic * or 1 tbsp. garlic",
        "amount": 1,
        "unit": "tablespoon",
        "name": "chopped roasted garlic * or 1 tbsp. garlic"
      },
      {
        "original": "1 teaspoon vinegar",
        "amount": 1,
        "unit": "teaspoon",
        "name": "vinegar"
      },
      {
        "original": "1/2 cup water",
        "amount": 0.5,
        "unit": "cup",
        "name": "water"
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "PLACE potatoes, carrots, celery and tomato in 3 1/2-qt. slow cooker. Season roast with pepper and place on top. MIX soup, water, pepper, garlic, basil, oregano, parsley and vinegar."
          },
          {
            "number": 2,
            "step": "Pour over all. COVER and cook on LOW 10 to 12 hr. or until done.** TIP: For thicker gravy, mix 1/4 cup all-purpose flour and 1/2 cup water."
          },
          {
            "number": 3,
            "step": "Remove roast from cooker. Stir flour mixture into cooker, cover and cook on HIGH about 10 min. or until mixture boils and thickens. *To roast garlic, place whole garlic bulb on piece of aluminum foil."
          },
          {
            "number": 4,
            "step": "Drizzle with vegetable oil and wrap. Roast at 350F. for 45 min. or until soft. Peel and chop garlic. **Or on HIGH 5 to 6 hr."
          }
        ]
      }
    ],
    "macros": {
      "calories": 428,
      "protein": 46,
      "carbs": 37,
      "fat": 10
    }
  },
  {
    "id": 30338,
    "title": "Spanish-Style Carrots and Cauliflower",
    "image": "https://img.spoonacular.com/recipes/30338-556x370.jpg",
    "readyInMinutes": 40,
    "servings": 4,
    "extendedIngredients": [
      {
        "original": "3 tablespoons almond butter",
        "amount": 3,
        "unit": "tablespoons",
        "name": "almond butter"
      },
      {
        "original": "2 large carrots, sliced 1/4 inch thick",
        "amount": 2
      },
      {
        "original": "1 head of cauliflower (2 pounds), florets sliced 1/3 inch thick",
        "amount": 1,
        "unit": "head",
        "name": "of cauliflower (2 pounds), florets sliced 1/3 inch thick"
      },
      {
        "original": "1 ounce spicy chorizo, minced",
        "amount": 1,
        "unit": "ounce",
        "name": "spicy chorizo, minced"
      },
      {
        "original": "Cilantro leaves, for garnish"
      },
      {
        "original": "2 garlic cloves, minced",
        "amount": 2
      },
      {
        "original": "1/4 teaspoon ground cumin",
        "amount": 0.25,
        "unit": "teaspoon",
        "name": "ground cumin"
      },
      {
        "original": "2 large red bell peppers",
        "amount": 2
      },
      {
        "original": "Salt and freshly ground pepper"
      },
      {
        "original": "1 cup plus 1 tablespoon water",
        "amount": 1,
        "unit": "cup",
        "name": "plus 1 tablespoon water"
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "Roast the bell peppers directly over a gas flame or under the broiler until charred all over."
          },
          {
            "number": 2,
            "step": "Transfer to a plate to cool. Peel, core and seed the peppers, then coarsely chop them."
          },
          {
            "number": 3,
            "step": "In a small skillet, cook the chorizo over moderate heat until crisp, about 4 minutes."
          },
          {
            "number": 4,
            "step": "Drain on paper towels."
          },
          {
            "number": 5,
            "step": "In a mini food processor, puree the roasted peppers with the almond butter, garlic, cumin and the 1 tablespoon of water. Scrape the sauce into a bowl and season with salt and pepper."
          },
          {
            "number": 6,
            "step": "In a large skillet, cover the carrots with 1/2 cup of the water and add a pinch of salt. Cover and cook over moderate heat for 5 minutes."
          },
          {
            "number": 7,
            "step": "Add the sliced cauliflower and the remaining 1/2 cup of water, cover and cook until just tender, about 5 minutes longer; drain."
          },
          {
            "number": 8,
            "step": "Transfer the vegetables to a platter and drizzle with some of the almond sauce. Top with the chorizo and cilantro and serve with the extra sauce."
          }
        ]
      }
    ],
    "macros": {
      "calories": 189,
      "protein": 9,
      "carbs": 22,
      "fat": 9
    }
  },
  {
    "id": 38925,
    "title": "Italian White Beans",
    "image": "https://img.spoonacular.com/recipes/38925-556x370.jpg",
    "readyInMinutes": 45,
    "servings": 4,
    "extendedIngredients": [
      {
        "original": "1 bay leaf?",
        "amount": 1
      },
      {
        "original": "1/2 cup good olive oil",
        "amount": 0.5,
        "unit": "cup",
        "name": "good olive oil"
      },
      {
        "original": "1 bunch Italian parsley",
        "amount": 1,
        "unit": "bunch",
        "name": "Italian parsley"
      },
      {
        "original": "2 tsps salt?",
        "amount": 2,
        "unit": "tsps",
        "name": "salt?"
      },
      {
        "original": "1 cup chicken or vegetable broth",
        "amount": 1,
        "unit": "cup",
        "name": "chicken or vegetable broth"
      },
      {
        "original": "1 lb small dried white beans",
        "amount": 1,
        "unit": "lb",
        "name": "small dried white beans"
      },
      {
        "original": "3 large cloves of garlic (1 left whole, 2 minced)",
        "amount": 3
      },
      {
        "original": "1/2 medium yellow or white onion, minced",
        "amount": 0.5
      }
    ],
    "analyzedInstructions": [],
    "macros": {
      "calories": 442,
      "protein": 27,
      "carbs": 72,
      "fat": 7
    }
  },
  {
    "id": 677801,
    "title": "P.F. Chang's Lettuce Wraps",
    "image": "https://img.spoonacular.com/recipes/677801-556x370.jpg",
    "readyInMinutes": 45,
    "servings": 2,
    "extendedIngredients": [
      {
        "original": "1/2-8oz can sliced water chestnuts, drained & chopped"
      },
      {
        "original": "2 teaspoons chili garlic sauce (or more if you like it hotter)",
        "amount": 2,
        "unit": "teaspoons",
        "name": "chili garlic sauce (or more if you like it hotter)"
      },
      {
        "original": "1\" knob ginger, peeled & minced"
      },
      {
        "original": "1\" knob ginger, peeled & minced"
      },
      {
        "original": "2 garlic cloves, minced",
        "amount": 2
      },
      {
        "original": "3 green onions, chopped",
        "amount": 3
      },
      {
        "original": "1lb ground chicken breast"
      },
      {
        "original": "1/2 Tablespoon honey",
        "amount": 0.5,
        "unit": "Tablespoon",
        "name": "honey"
      },
      {
        "original": "10-12 large outer lettuce leaves, rinsed and patted dry"
      },
      {
        "original": "1/2 onion, minced",
        "amount": 0.5
      },
      {
        "original": "1 Tablespoon peanut butter",
        "amount": 1,
        "unit": "Tablespoon",
        "name": "peanut butter"
      },
      {
        "original": "1/4 cup peanuts, chopped",
        "amount": 0.25,
        "unit": "cup",
        "name": "peanuts, chopped"
      },
      {
        "original": "1 Tablespoon + 1 teaspoon rice vinegar",
        "amount": 1,
        "unit": "Tablespoon",
        "name": "+ 1 teaspoon rice vinegar"
      },
      {
        "original": "salt & pepper"
      },
      {
        "original": "1 Tablespoon sesame oil",
        "amount": 1,
        "unit": "Tablespoon",
        "name": "sesame oil"
      },
      {
        "original": "2-1/2 Tablespoons gluten-free Tamari or soy sauce"
      },
      {
        "original": "1/2 Tablespoon water",
        "amount": 0.5,
        "unit": "Tablespoon",
        "name": "water"
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "Heat a large, non-stick skillet on high."
          },
          {
            "number": 2,
            "step": "Add chicken, onion, salt & pepper, then cook until chicken is nearly done, stirring often to break up the meat."
          },
          {
            "number": 3,
            "step": "Add garlic and ginger then continue cooking until chicken is no longer pink.Meanwhile, in a microwave safe bowl, combine gluten-free Tamari or soy sauce, rice vinegar, oil, peanut butter, water, honey, chili garlic sauce and pepper. Microwave for 20 seconds, then stir until smooth."
          },
          {
            "number": 4,
            "step": "Add into the skillet and stir to combine."
          },
          {
            "number": 5,
            "step": "Add green onions and water chestnuts into the skillet then cook for 1-2 minutes until the onions are soft and the water chestnuts are heated through."
          },
          {
            "number": 6,
            "step": "Sprinkle with chopped peanuts, and serve with cold lettuce leaves."
          }
        ]
      }
    ],
    "macros": {
      "calories": 552,
      "protein": 59,
      "carbs": 21,
      "fat": 26
    }
  },
  {
    "id": 716873,
    "title": "Slow Cooker Jalapeño Popper Chicken Taquitos",
    "image": "https://img.spoonacular.com/recipes/716873-556x370.jpg",
    "readyInMinutes": 360,
    "servings": 4,
    "extendedIngredients": [
      {
        "original": "3-4 chicken breasts, frozen or thawed"
      },
      {
        "original": "8 ounces cream cheese",
        "amount": 8,
        "unit": "ounces",
        "name": "cream cheese"
      },
      {
        "original": "1 teaspoon cumin",
        "amount": 1,
        "unit": "teaspoon",
        "name": "cumin"
      },
      {
        "original": "1 teaspoon garlic powder",
        "amount": 1,
        "unit": "teaspoon",
        "name": "garlic powder"
      },
      {
        "original": "1/3 cup jarred whole or sliced jalapeños, roughly chopped (or more, to taste)",
        "amount": 0.3333333333333333,
        "unit": "cup",
        "name": "jarred whole or sliced jalapeños, roughly chopped (or more, to taste)"
      },
      {
        "original": "1 teaspoon salt",
        "amount": 1,
        "unit": "teaspoon",
        "name": "salt"
      },
      {
        "original": "1½ cups shredded cheese (colby jack, monterey jack, Mexican blend, mozzarella - use your favorite!)"
      },
      {
        "original": "16 taco-sized tortillas (I prefer flour but corn tortillas also work well)",
        "amount": 16
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "Add chicken,  cup water, cream cheese, jalapeos, garlic powder, salt, and cumin to crockpot. Cover and cook on low for 6-8 hours or on high 3-4 hours. (lesser times are for thawed chicken, greater times for frozen chicken)minutes before serving, preheat the oven to 425 and grease a baking sheet with cooking spray.Use two forks to shred chicken and stir it in with the other contents of the crockpot."
          },
          {
            "number": 2,
            "step": "Heat tortillas in the microwave for a few seconds to soften them up, this will make them easier to work with."
          },
          {
            "number": 3,
            "step": "Sprinkle cheese in the middle of each tortilla (just divide the cheese evenly between all of the tortillas).Top cheese with 2-3 tablespoons of shredded chicken mixture."
          },
          {
            "number": 4,
            "step": "Roll tortillas tightly into a log-shape taquito."
          },
          {
            "number": 5,
            "step": "Place taquitos on baking sheet and spray heavily with cooking spray."
          },
          {
            "number": 6,
            "step": "Bake 10-15 minutes until cheese is melty and tortillas begin to brown. (For crispier taquitos, switch the oven to broil for 2-3 minutes - watch carefully so they don't burn!)"
          },
          {
            "number": 7,
            "step": "Serve warm with dipping sauces and toppings if desired."
          }
        ]
      }
    ],
    "macros": {
      "calories": 891,
      "protein": 59,
      "carbs": 65,
      "fat": 43
    }
  },
  {
    "id": 791498,
    "title": "Mexican Dorito Casserole",
    "image": "https://img.spoonacular.com/recipes/791498-556x370.jpg",
    "readyInMinutes": 40,
    "servings": 6,
    "extendedIngredients": [
      {
        "original": "1 can Ro-tel tomatoes (canned tomatoes with jalepenos-mild)",
        "amount": 1,
        "unit": "can",
        "name": "Ro-tel tomatoes (canned tomatoes with jalepenos-mild)"
      },
      {
        "original": "1 can cream of chicken soup",
        "amount": 1,
        "unit": "can",
        "name": "cream of chicken soup"
      },
      {
        "original": "1/2 cup milk",
        "amount": 0.5,
        "unit": "cup",
        "name": "milk"
      },
      {
        "original": "Bag of regular nacho cheese doritos"
      },
      {
        "original": "1 c. shredded cheese (or more if you are a cheese hound)",
        "amount": 1
      },
      {
        "original": "2 c. shredded cooked chicken",
        "amount": 2
      },
      {
        "original": "1/2 cup sour cream",
        "amount": 0.5,
        "unit": "cup",
        "name": "sour cream"
      },
      {
        "original": "1/2 packet taco seasoning (or more- to taste)",
        "amount": 0.5
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "Pre-heat oven to 350-f degrees.In a mixing bowl, combine all ingredients except doritos.In a greased 2 qt baking dish, put a layer of crushed doritos (about 2 cups), then a layer of the chicken mixture. Repeat once more, ending with a layer of chicken mixture. Top with more shredded cheese, cover, and bake for 30-35 minutes, till bubbling hot."
          }
        ]
      }
    ],
    "macros": {
      "calories": 258,
      "protein": 19,
      "carbs": 13,
      "fat": 15
    }
  },
  {
    "id": 840670,
    "title": "Pizza Margherita Grilled Cheese",
    "image": "https://img.spoonacular.com/recipes/840670-556x370.jpg",
    "readyInMinutes": 30,
    "servings": 4,
    "extendedIngredients": [
      {
        "original": "1 cup basil leaves",
        "amount": 1,
        "unit": "cup",
        "name": "basil leaves"
      },
      {
        "original": "3 tablespoons butter, melted",
        "amount": 3,
        "unit": "tablespoons",
        "name": "butter, melted"
      },
      {
        "original": "14.5 ounces fire-roasted canned tomatoes",
        "amount": 14.5,
        "unit": "ounces",
        "name": "fire-roasted canned tomatoes"
      },
      {
        "original": "16 ounces fresh mozzarella cheese, sliced",
        "amount": 16,
        "unit": "ounces",
        "name": "fresh mozzarella cheese, sliced"
      },
      {
        "original": "1 large garlic clove, minced",
        "amount": 1
      },
      {
        "original": "1 teaspoon olive oil",
        "amount": 1,
        "unit": "teaspoon",
        "name": "olive oil"
      },
      {
        "original": "¼ teaspoons salt"
      },
      {
        "original": "8 slices sourdough bread",
        "amount": 8,
        "unit": "slices",
        "name": "sourdough bread"
      },
      {
        "original": "1 tablespoon sugar",
        "amount": 1,
        "unit": "tablespoon",
        "name": "sugar"
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "In a small sauce pan, heat olive oil and garlic over a medium heat."
          },
          {
            "number": 2,
            "step": "Saute until softened, about 1 minute."
          },
          {
            "number": 3,
            "step": "Add tomatoes, salt and sugar. Simmer for 8-10 minutes. Set aside."
          },
          {
            "number": 4,
            "step": "Heat a large cast-iron skillet or griddle to a medium heat."
          },
          {
            "number": 5,
            "step": "Spread about 2 tablespoons of sauce on each slice of bread. Top with four ounces of slices of cheese. Top with 4-5 leaves of basil."
          },
          {
            "number": 6,
            "step": "Drizzle with a little bit of olive oil. Season with salt and pepper."
          },
          {
            "number": 7,
            "step": "Place top of bread, sauce side down on cheese and basil."
          },
          {
            "number": 8,
            "step": "Brush tops with butter. Season with a bit of salt and pepper."
          },
          {
            "number": 9,
            "step": "Place sandwich butter side down in heated skillet (work in batched if needed), brush other side with butter. Cook until golden brown and crispy on each side and the cheese is melted. (If you are having a hard time getting the cheese to melt, pop into a 350 degree oven for a few minutes."
          }
        ]
      }
    ],
    "macros": {
      "calories": 810,
      "protein": 40,
      "carbs": 77,
      "fat": 38
    }
  },
  {
    "id": 909604,
    "title": "One Pot Chicken & Potatoes",
    "image": "https://img.spoonacular.com/recipes/909604-556x370.jpg",
    "readyInMinutes": 85,
    "servings": 4,
    "extendedIngredients": [
      {
        "original": "5-6 carrots, cut in 1-2 inch pieces"
      },
      {
        "original": "8 chicken thighs",
        "amount": 8
      },
      {
        "original": "Black ground pepper"
      },
      {
        "original": "4 tsp ground pepper or 5 cloves garlic, crushed",
        "amount": 4,
        "unit": "tsp",
        "name": "ground pepper or 5 cloves garlic, crushed"
      },
      {
        "original": "Kosher salt"
      },
      {
        "original": "3-4 Tbsp olive oil."
      },
      {
        "original": "1 onion, cut in quarters",
        "amount": 1
      },
      {
        "original": "6-8 large potatoes, cut in quarters or halves"
      },
      {
        "original": "15-20 garlic cloves, whole"
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "Preheat oven to 375F. Line a rimmed 12in x 18in baking sheet with foil or even better, parchment paper.Thoroughly wash the potatoes & carrots with a scrubber and cut them in smaller pieces. Pat dry with a paper towel.Pat dry chicken with paper towel."
          },
          {
            "number": 2,
            "step": "Add chicken, potatoes and carrots, onion & garlic to the lined rimmed baking dish and sprinkle with salt, ground pepper and garlic."
          },
          {
            "number": 3,
            "step": "Drizzle with olive oil. Carefully toss everything to coat."
          },
          {
            "number": 4,
            "step": "Place in the oven and bake for 1 hour 20 minutes. Check for doneness -if the potatoes and chicken thighs are soft and easily pierced with the fork they are ready.If the chicken and potatoes have not browned up as much as you would like, turn the broil setting on and broil for 5 minutes. Watch carefully, or they will burn."
          },
          {
            "number": 5,
            "step": "Remove from the oven and serve right away in the baking pan or transfer to a warm serving plate."
          }
        ]
      }
    ],
    "macros": {
      "calories": 1078,
      "protein": 50,
      "carbs": 112,
      "fat": 49
    }
  },
  {
    "id": 945221,
    "title": "Watching What I Eat: Peanut Butter Banana Oat Breakfast Cookies with Carob / Chocolate Chips",
    "image": "https://img.spoonacular.com/recipes/945221-556x370.jpg",
    "readyInMinutes": 45,
    "servings": 16,
    "extendedIngredients": [
      {
        "original": "2 ripe bananas, mashed until smooth & creamy",
        "amount": 2
      },
      {
        "original": "1 tsp butter flavor extract ** (optional)",
        "amount": 1,
        "unit": "tsp",
        "name": "butter flavor extract ** (optional)"
      },
      {
        "original": "1/4 cup carob or chocolate chips (**optional)",
        "amount": 0.25,
        "unit": "cup",
        "name": "carob or chocolate chips (**optional)"
      },
      {
        "original": "1/3 cup peanut butter - creamy or chunky",
        "amount": 0.3333333333333333,
        "unit": "cup",
        "name": "peanut butter - creamy or chunky"
      },
      {
        "original": "1/4 cup chopped nuts (peanut, walnut, or your favorite)",
        "amount": 0.25,
        "unit": "cup",
        "name": "chopped nuts (peanut, walnut, or your favorite)"
      },
      {
        "original": "1 1/2 cups quick oatmeal - uncooked (or use old fashioned oats for more oatmeal texture)",
        "amount": 1.5,
        "unit": "cups",
        "name": "quick oatmeal - uncooked (or use old fashioned oats for more oatmeal texture)"
      },
      {
        "original": "2/3 cup unsweetened applesauce",
        "amount": 0.6666666666666666,
        "unit": "cup",
        "name": "unsweetened applesauce"
      },
      {
        "original": "1 tsp vanilla extract",
        "amount": 1,
        "unit": "tsp",
        "name": "vanilla extract"
      },
      {
        "original": "1 scoop vanilla protein powder ** (can be made without, cookie will just be lower in protein)",
        "amount": 1
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "Preheat heat oven to 350 degrees.In a large bowl, mix mashed banana & peanut butter until completely combined then add in the applesauce, vanilla protein powder & the extract(s) ~ mix again until all are completely combined."
          },
          {
            "number": 2,
            "step": "Add in the oatmeal & nuts to the banana mixture & combine. (** add the optional carob / chocolate chips at this time if you want them mixed throughout)"
          },
          {
            "number": 3,
            "step": "Let dough rest for 10 minutes.Drop cookie dough, by spoonfuls, onto a parchment paper lined cookie sheet & flatten cookies into circles. (** if you just want the carob / chocolate chips on the top of the cookies, add now)"
          },
          {
            "number": 4,
            "step": "Bake cookies approx. 20-30 minutes (some like their cookies less cooked, some cooked more - try it both ways to find which works best for your tastes) or until golden brown & done."
          },
          {
            "number": 5,
            "step": "Remove from oven & let rest on cookie sheet for 5 minutes, then move to cooling rack. (if you want the traditional fork tong marks on the cookies, use a pizza cutter or sharp knife to score the tops of the cookies while they're still warm)When cookies are completely cool, store in a covered container. Enjoy!...or with a cuppa tea."
          }
        ]
      }
    ],
    "macros": {
      "calories": 103,
      "protein": 4,
      "carbs": 11,
      "fat": 5
    }
  },
  {
    "id": 968153,
    "title": "Split Pea and Ham Bone Soup",
    "image": "https://img.spoonacular.com/recipes/968153-556x370.jpg",
    "readyInMinutes": 120,
    "servings": 6,
    "extendedIngredients": [
      {
        "original": "¼ tsp freshly ground black pepper plus more to taste"
      },
      {
        "original": "1 ¼ cups diced carrots (1 large carrot)"
      },
      {
        "original": "1 cup finely chopped celery, about 2 medium celery stalks",
        "amount": 1,
        "unit": "cup",
        "name": "finely chopped celery, about 2 medium celery stalks"
      },
      {
        "original": "1 left over ham bone",
        "amount": 1
      },
      {
        "original": "1 onion, chopped",
        "amount": 1
      },
      {
        "original": "Salt to taste"
      },
      {
        "original": "8 cups water",
        "amount": 8,
        "unit": "cups",
        "name": "water"
      },
      {
        "original": "2 cups yellow dried split peas, sorted and rinsed",
        "amount": 2,
        "unit": "cups",
        "name": "yellow dried split peas, sorted and rinsed"
      }
    ],
    "analyzedInstructions": [
      {
        "steps": [
          {
            "number": 1,
            "step": "In a soup pot, combine together the split peas and water. Bring the mixture to a boil."
          },
          {
            "number": 2,
            "step": "Remove from the heat. Cover and let stand for 1 hour."
          },
          {
            "number": 3,
            "step": "After an hour, return the pot to the heat."
          },
          {
            "number": 4,
            "step": "Add the onion, celery, pepper and ham bone, and bring to a boil. Reduce the heat to medium, cover and cook, stirring occasionally for 40 minutes or until the split peas are tender."
          },
          {
            "number": 5,
            "step": "Remove the ham bone from the soup and pull off meat from the bone. Return the meat to the soup and discard the bone."
          },
          {
            "number": 6,
            "step": "Add the carrots and cook for 20 minutes or until the carrots are tender and soup has thickens. Season with salt and pepper."
          }
        ]
      }
    ],
    "macros": {
      "calories": 245,
      "protein": 17,
      "carbs": 44,
      "fat": 1
    }
  }
]
