#!/usr/bin/env node
// Refreshes/extends app/content/recipe-data.ts from the Spoonacular API.
//
// The curated library's *fact* data comes from Spoonacular (license it on the recipe page
// via the source link); the *editorial* layer lives in app/content/recipes.ts and is never
// overwritten here.
//
// Usage:
//   node scripts/snapshot-recipes.mjs          # refresh existing curated IDs, keep order
//   node scripts/snapshot-recipes.mjs --add 20 # also add up to 20 new from top sorted lists
//   node scripts/snapshot-recipes.mjs --ids 1,2,3 # add specific IDs
//
// Requires SPOONACULAR_API_KEY (reads process.env or .env). New recipes land in
// recipe-data.ts with no editorial entry — add one in recipes.ts (or accept the
// bare-recipe render) before deploying.

import { existsSync, readFileSync, writeFileSync } from 'node:fs'

const DATA_FILE = new URL('../app/content/recipe-data.ts', import.meta.url)
const BASE = 'https://api.spoonacular.com'

function env(name) {
  if (process.env[name]) return process.env[name]
  try {
    const dotenv = readFileSync(new URL('../.env', import.meta.url), 'utf8')
    const hit = dotenv.match(new RegExp(`^${name}=(.*)$`, 'm'))
    return hit?.[1]?.trim()
  } catch {
    return undefined
  }
}

const KEY = env('SPOONACULAR_API_KEY')
if (!KEY) {
  console.error('SPOONACULAR_API_KEY not found in env or .env — cannot reach the API.')
  process.exit(1)
}

function existingIds() {
  const src = readFileSync(DATA_FILE, 'utf8')
  return [...src.matchAll(/"id":\s*(\d+)/g)].map((m) => Number(m[1]))
}

async function api(path) {
  const url = new URL(path, BASE)
  url.searchParams.set('apiKey', KEY)
  const res = await fetch(url.toString())
  if (!res.ok) throw new Error(`Spoonacular ${res.status} for ${path}`)
  return res.json()
}

function extractMacros(nutrition) {
  const find = (name) => {
    const n = nutrition?.nutrients?.find((x) => x?.name === name)
    return typeof n?.amount === 'number' ? n.amount : undefined
  }
  const m = { calories: find('Calories'), protein: find('Protein'), carbs: find('Carbohydrates'), fat: find('Fat') }
  return m.calories == null && m.protein == null && m.carbs == null && m.fat == null ? undefined : m
}

function toSnapshot(recipe) {
  const normalized = []
  for (const ing of recipe.extendedIngredients ?? []) {
    const row = {
      id: ing.id,
      name: ing.name,
      nameClean: ing.nameClean,
      original: ing.original,
      amount: ing.amount,
      unit: ing.unit,
      unitShort: ing.unitShort,
      measures: ing.measures,
    }
    for (const k of Object.keys(row)) if (row[k] == null || row[k] === '') delete row[k]
    normalized.push(row)
  }
  const steps = (recipe.analyzedInstructions?.[0]?.steps ?? []).map((s) => ({ number: s?.number ?? 1, step: String(s?.step ?? '').trim() }))
  return {
    id: recipe.id,
    title: recipe.title,
    image: recipe.image || undefined,
    readyInMinutes: recipe.readyInMinutes,
    servings: recipe.servings,
    extendedIngredients: normalized,
    analyzedInstructions: steps.length ? [{ steps }] : [],
    macros: extractMacros(recipe.nutrition),
  }
}

async function fetchByIds(ids) {
  const out = []
  for (const id of [...new Set(ids)]) {
    try {
      const recipe = await api(`/recipes/${id}/information?includeNutrition=true`)
      out.push(toSnapshot(recipe))
    } catch (err) {
      console.warn(`  skipped ${id}: ${err.message}`)
    }
  }
  return out
}

async function suggestedIds(limit) {
  const out = new Set(existingIds())
  for (const sort of ['popularity', 'healthiness']) {
    const params = new URLSearchParams({ sort, sortDirection: 'desc', number: String(limit), addRecipeInformation: 'true' })
    const json = await api(`/recipes/complexSearch?${params}`)
    for (const r of json?.results ?? []) if (r?.id) out.add(r.id)
  }
  return [...out].slice(0, existingIds().length + limit)
}

async function main() {
  const args = process.argv.slice(2)
  const addFlag = args.find((a) => a.startsWith('--add='))
  const add = addFlag ? Number(addFlag.split('=')[1]) : 0
  const idsFlag = args.find((a) => a.startsWith('--ids='))
  const ids = idsFlag ? idsFlag.split('=')[1].split(',').map(Number).filter(Boolean) : []

  let targets = existingIds()
  if (ids.length) targets = [...targets, ...ids]
  else if (add > 0) targets = (await suggestedIds(add)).slice(0, targets.length + add)

  console.log(`Fetching ${targets.length} recipes from Spoonacular…`)
  const fresh = await fetchByIds(targets)

  // Keep existing entries in their original order; append anything new.
  const current = existingIds()
  const newOnes = fresh.filter((r) => !current.includes(r.id))
  const ordered = [...fresh.filter((r) => current.includes(r.id)).sort((a, b) => current.indexOf(a.id) - current.indexOf(b.id)), ...newOnes]

  const body =
    `// Generated by scripts/snapshot-recipes.mjs (${new Date().toISOString().slice(0, 10)}) — DO NOT hand-edit.\n` +
    `// Curated library snapshots from the Spoonacular API. Editorial copy lives in recipes.ts.\n\n` +
    `import type { CuratedRecipeData } from './types'\n\n` +
    `export const recipeData: CuratedRecipeData[] = ` +
    JSON.stringify(ordered, null, 2) +
    `\n`
  writeFileSync(DATA_FILE, body)
  console.log(`Wrote ${ordered.length} curated recipe snapshots (${newOnes.length} new) to app/content/recipe-data.ts`)
  if (newOnes.length) console.log('Remember: give each new recipe an editorial entry in app/content/recipes.ts (intro/tips/faqs/collections).')
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})